// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_bigquerylink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BigquerylinkResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Output only. Time when the link was created.",
				MarkdownDescription: "Output only. Time when the link was created.",
			},
			"daily_export": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set true, enables daily data export to the linked Google Cloud project.",
				MarkdownDescription: "If set true, enables daily data export to the linked Google Cloud project.",
				Default:             booldefault.StaticBool(false),
			},
			"dataset_location": schema.StringAttribute{
				Required:            true,
				Description:         "Required. Immutable. The geographic location where the created BigQuery dataset should reside. See https://cloud.google.com/bigquery/docs/locations for supported locations.",
				MarkdownDescription: "Required. Immutable. The geographic location where the created BigQuery dataset should reside. See https://cloud.google.com/bigquery/docs/locations for supported locations.",
			},
			"exclude_events": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The list of event names that will be excluded from exports",
				MarkdownDescription: "The list of event names that will be excluded from exports",
			},
			"export_streams": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The list of streams under the parent property for which data will be exported. Format: properties/{property_id}/dataStreams/{stream_id} Example: ['properties/1000/dataStreams/2000']",
				MarkdownDescription: "The list of streams under the parent property for which data will be exported. Format: properties/{property_id}/dataStreams/{stream_id} Example: ['properties/1000/dataStreams/2000']",
				Validators: []validator.List{
					listvalidator.ValueStringsAre(stringvalidator.RegexMatches(regexp.MustCompile(`properties/\w./dataStreams/\w.`), "Must match Format: 'properties/{property_id}/dataStreams/{stream_id}'")),
				},
			},
			"fresh_daily_export": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set true, enables fresh daily export to the linked Google Cloud project.",
				MarkdownDescription: "If set true, enables fresh daily export to the linked Google Cloud project.",
				Default:             booldefault.StaticBool(false),
			},
			"include_advertising_id": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set true, exported data will include advertising identifiers for mobile app streams.",
				MarkdownDescription: "If set true, exported data will include advertising identifiers for mobile app streams.",
				Default:             booldefault.StaticBool(false),
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Output only. Resource name of this BigQuery link. Format: 'properties/{property_id}/bigQueryLinks/{bigquery_link_id}' Format: 'properties/1234/bigQueryLinks/abc567'",
				MarkdownDescription: "Output only. Resource name of this BigQuery link. Format: 'properties/{property_id}/bigQueryLinks/{bigquery_link_id}' Format: 'properties/1234/bigQueryLinks/abc567'",
			},
			"project": schema.StringAttribute{
				Required:            true,
				Description:         "Immutable. The linked Google Cloud project ID. Once this resource has been created, the returned project will always have a project that contains a project number. Format: 'projects/{project number}' Example: 'projects/1234'",
				MarkdownDescription: "Immutable. The linked Google Cloud project ID. Once this resource has been created, the returned project will always have a project that contains a project number. Format: 'projects/{project number}' Example: 'projects/1234'",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`projects/\w.`), "Must match Format: 'projects/{project number}'"),
				},
			},
			"property_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Google Analytics property",
				MarkdownDescription: "The Google Analytics property",
			},
			"streaming_export": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "If set true, enables streaming export to the linked Google Cloud project.",
				MarkdownDescription: "If set true, enables streaming export to the linked Google Cloud project.",
				Default:             booldefault.StaticBool(false),
			},
		},
	}
}

type BigquerylinkModel struct {
	CreateTime           types.String `tfsdk:"create_time"`
	DailyExport          types.Bool   `tfsdk:"daily_export"`
	DatasetLocation      types.String `tfsdk:"dataset_location"`
	ExcludeEvents        types.List   `tfsdk:"exclude_events"`
	ExportStreams        types.List   `tfsdk:"export_streams"`
	FreshDailyExport     types.Bool   `tfsdk:"fresh_daily_export"`
	IncludeAdvertisingId types.Bool   `tfsdk:"include_advertising_id"`
	Name                 types.String `tfsdk:"name"`
	Project              types.String `tfsdk:"project"`
	PropertyId           types.String `tfsdk:"property_id"`
	StreamingExport      types.Bool   `tfsdk:"streaming_export"`
}
