// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_datastreams

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DatastreamsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data_streams": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"display_name": schema.StringAttribute{
							Optional: true,
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DataStreamsType{
						ObjectType: types.ObjectType{
							AttrTypes: DataStreamsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Ouput: The list of data  that will be excluded from exports",
				MarkdownDescription: "Ouput: The list of data  that will be excluded from exports",
			},
			"property_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Google Analytics property",
				MarkdownDescription: "The Google Analytics property",
			},
		},
		Description: "List all datastreams for a property_id",
	}
}

type DatastreamsModel struct {
	DataStreams types.List   `tfsdk:"data_streams"`
	PropertyId  types.String `tfsdk:"property_id"`
}

var _ basetypes.ObjectTypable = DataStreamsType{}

type DataStreamsType struct {
	basetypes.ObjectType
}

func (t DataStreamsType) Equal(o attr.Type) bool {
	other, ok := o.(DataStreamsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataStreamsType) String() string {
	return "DataStreamsType"
}

func (t DataStreamsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	displayNameAttribute, ok := attributes["display_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_name is missing from object`)

		return nil, diags
	}

	displayNameVal, ok := displayNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_name expected to be basetypes.StringValue, was: %T`, displayNameAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataStreamsValue{
		DisplayName:     displayNameVal,
		Name:            nameVal,
		DataStreamsType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDataStreamsValueNull() DataStreamsValue {
	return DataStreamsValue{
		state: attr.ValueStateNull,
	}
}

func NewDataStreamsValueUnknown() DataStreamsValue {
	return DataStreamsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataStreamsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataStreamsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataStreamsValue Attribute Value",
				"While creating a DataStreamsValue value, a missing attribute value was detected. "+
					"A DataStreamsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataStreamsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataStreamsValue Attribute Type",
				"While creating a DataStreamsValue value, an invalid attribute value was detected. "+
					"A DataStreamsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataStreamsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataStreamsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataStreamsValue Attribute Value",
				"While creating a DataStreamsValue value, an extra attribute value was detected. "+
					"A DataStreamsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataStreamsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataStreamsValueUnknown(), diags
	}

	displayNameAttribute, ok := attributes["display_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_name is missing from object`)

		return NewDataStreamsValueUnknown(), diags
	}

	displayNameVal, ok := displayNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_name expected to be basetypes.StringValue, was: %T`, displayNameAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDataStreamsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewDataStreamsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewDataStreamsValueUnknown(), diags
	}

	return DataStreamsValue{
		DisplayName:     displayNameVal,
		Name:            nameVal,
		DataStreamsType: typeVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDataStreamsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataStreamsValue {
	object, diags := NewDataStreamsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataStreamsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataStreamsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataStreamsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataStreamsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataStreamsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataStreamsValueMust(DataStreamsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataStreamsType) ValueType(ctx context.Context) attr.Value {
	return DataStreamsValue{}
}

var _ basetypes.ObjectValuable = DataStreamsValue{}

type DataStreamsValue struct {
	DisplayName     basetypes.StringValue `tfsdk:"display_name"`
	Name            basetypes.StringValue `tfsdk:"name"`
	DataStreamsType basetypes.StringValue `tfsdk:"type"`
	state           attr.ValueState
}

func (v DataStreamsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["display_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.DisplayName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["display_name"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.DataStreamsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataStreamsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataStreamsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataStreamsValue) String() string {
	return "DataStreamsValue"
}

func (v DataStreamsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"display_name": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"type":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"display_name": v.DisplayName,
			"name":         v.Name,
			"type":         v.DataStreamsType,
		})

	return objVal, diags
}

func (v DataStreamsValue) Equal(o attr.Value) bool {
	other, ok := o.(DataStreamsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DisplayName.Equal(other.DisplayName) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.DataStreamsType.Equal(other.DataStreamsType) {
		return false
	}

	return true
}

func (v DataStreamsValue) Type(ctx context.Context) attr.Type {
	return DataStreamsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataStreamsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"display_name": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"type":         basetypes.StringType{},
	}
}
